version: "3.5"
services:
  engine:
    image: 5minds/engine:15.1.2
    ports:
      - 8000:8000
    volumes:
      - ./.processcube/engine/config/config.json:/etc/engine/config/config.json:ro
      - ./.processcube/engine/db:/root/.config/AtlasEngineFullstackServer/databases:rw
      - ./processes:/processes:ro
    command: --seed-dir=/processes --port 8000
    environment:
      CONFIG_PATH: /etc/engine/config/config.json

  portal:
    image: 5minds/portal:4.0.2
    volumes:
      - ./.processcube/portal/theme.css:/etc/portal/config/theme.css:ro
      - ./.processcube/portal/config.json:/etc/portal/config/config.json:ro
      - ./.processcube/portal/assets:/etc/portal/config/assets:ro
      - ./.processcube/portal/translation:/etc/portal/config/translation:ro
    command: "--config-path /etc/portal/config/config.json --theme /etc/portal/config/theme.css --assets /etc/portal/config/assets"
    ports:
      - 8082:8082

  app:
    image: source_name_lower_docker
    build:
      context: ./
      dockerfile: apps/Template.ProcessCube.Project/Dockerfile
    volumes:
      - ./apps:/apps
    ports:
      - 5111:5111
    working_dir: /apps/Template.ProcessCube.Project
    command: dotnet run

  frontend:
    image: source_name_lower_docker
    volumes:
      - ./apps/Template.ProcessCube.Project/frontend:/apps/Template.ProcessCube.Project/frontend
    working_dir: /apps/Template.ProcessCube.Project/frontend/
    command: npm start
    ports:
      - 3000:3000
