version: '3.5'
services:
  test:
    container_name: source_name_lower_docker_tests
    image: ghcr.io/5minds/testimage:0.0.1
    depends_on:
      - app
      - frontend
      - engine
      - portal
    network_mode: host
    volumes:
      - ./integration-tests:/opt/robotframework/tests
      - ./testresults:/opt/robotframework/reports
    user: "${UID}:${GID}"
    privileged: true
    shm_size: 2gb
    extra_hosts:
      - "engine:127.0.0.1"
      - "localhost:127.0.0.1"
    ipc: host
