import Link from 'next/link'
import './styles/main.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-col laptop:flex-row  min-h-screen w-full'>
        <div className='bg-lime-200 w-1/5'>
          <nav className='text-2xl text-center flex flex-col gap-4 justify-around'>
            <Link className='p-4 bg-lime-200 hover:bg-lime-300 active:bg-lime-300 rounded-md drop-shadow-lg active:drop-shadow-none' href='/'>StartDialog</Link>
            <Link className='p-4 bg-lime-200 hover:bg-lime-300 active:bg-lime-300 rounded-md drop-shadow-lg active:drop-shadow-none' href='/server'>Server</Link>
          </nav>
        </div>
        <div className='bg-gray-500 w-4/5'>
          {children}
        </div>
      </body>
    </html>
  )
}
